name: "Hello Action POC"
description: "A simple action to greet someone"
author: "Neo Spark"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
runs:
  using: "node16"
  main: "index.js"
branding:
  icon: "smile"
  color: "yellow"
